import { swatch, fileIcon, ai, logoShirt, stylishShirt } from '../assets';

export const EditorTabs = [
  {
    name: 'colorpicker',
    icon: swatch,
  },
  {
    name: 'filepicker',
    icon: fileIcon,
  },
  {
    name: 'aipicker',
    icon: ai,
  },
];

export const FilterTabs = [
  {
    name: 'logoShirt',
    icon: logoShirt,
  },
  {
    name: 'stylishShirt',
    icon: stylishShirt,
  },
];

export const DecalTypes = {
  logo: {
    stateProperty: 'logoDecal',
    filterTab: 'logoShirt',
  },
  full: {
    stateProperty: 'fullDecal',
    filterTab: 'stylishShirt',
  },
};

export const surpriseMePrompts = [
  'A bold, geometric pattern of overlapping triangles, creating a sense of depth and movement on the shirt.',
  'An abstract design inspired by the night sky, featuring swirling galaxies and stars in shades of blue and black.',
  'A minimalist design featuring a series of thin, parallel lines in a gradient of warm colors, evoking the sensation of a sunrise or sunset.',
  'A repeating pattern of stylized, interlocking anchors in shades of navy blue and white, perfect for a nautical or beach-themed shirt.',
  'A graphic design inspired by the natural world, featuring silhouettes of leaves, branches, and wildlife in muted earth tones.',
  'A bold, graphic pattern of stylized lightning bolts in bright colors, creating a sense of energy and excitement.',
  'A playful design featuring a repeating pattern of cartoon-style robots in a variety of poses and colors, perfect for a fun and lighthearted T-shirt.',
  'An abstract design featuring intersecting lines and shapes in bold, contrasting colors, creating a sense of visual tension and movement.',
  'A repeating pattern of retro-inspired geometric shapes in bright, eye-catching colors, perfect for a vintage-inspired look.',
  'A graphic design inspired by street art and graffiti, featuring bold, stylized lettering and colorful spray-painted patterns.',
  'A graphic design featuring a series of stylized skulls in a range of vibrant colors, perfect for a edgy or rock-inspired shirt.',
  'A repeating pattern of intricate, interlocking gears and cogs in shades of brass and copper, perfect for a steampunk-themed T-shirt.',
  'An abstract design featuring a chaotic pattern of splattered paint in bright, bold colors, creating a sense of energy and movement.',
  'A minimalist design featuring a repeating pattern of simple, geometric shapes in shades of black and white, perfect for a clean and modern look.',
  'A graphic design featuring a series of vintage-inspired cars and motorcycles in bold, contrasting colors, perfect for a retro-inspired T-shirt.',
  'A repeating pattern of stylized skulls and crossbones in shades of grey and black, perfect for a gothic or pirate-themed shirt.',
  'A playful design featuring a repeating pattern of colorful cartoon-style fruits, perfect for a fun and summery T-shirt.',
  'An abstract design featuring a series of overlapping circles and arcs in shades of blue and green, evoking a sense of the ocean or sea.',
  'A repeating pattern of stylized camo print in shades of green and brown, perfect for a military-inspired T-shirt.',
  'A graphic design featuring a series of abstract, swirling shapes in bold, contrasting colors, creating a sense of movement and energy.',
  'A graphic design featuring a series of bold, stylized flames in shades of red and orange, perfect for a hot rod or racing-themed T-shirt.',
  'A repeating pattern of stylized, geometric animal prints in shades of black and white, perfect for a modern and edgy look.',
  'An abstract design featuring a series of overlapping, interlocking circles in shades of purple and pink, creating a sense of depth and dimension.',
  'A playful design featuring a repeating pattern of cartoon-style robots and spaceships in bright, vibrant colors, perfect for a sci-fi-inspired T-shirt.',
  'A minimalist design featuring a series of simple, overlapping triangles in shades of grey and black, creating a clean and modern look.',
  'A graphic design featuring a series of stylized, vintage-inspired tattoos in bold, contrasting colors, perfect for a rocker or biker-themed shirt.',
  'A repeating pattern of stylized, interlocking chains in shades of silver and black, perfect for a bold and edgy look.',
  'An abstract design featuring a series of swirling, organic shapes in shades of blue and green, evoking a sense of nature and the outdoors.',
  'A graphic design featuring a series of bold, abstract shapes in shades of black and white, creating a striking and eye-catching look.',
  'A repeating pattern of stylized, interlocking skulls in shades of black and white, perfect for a gothic or rocker-inspired T-shirt.',
  'A bold, stylized lettering logo in a sans-serif font with a modern twist, featuring a vibrant color scheme and strong typography.',
  'A repeating pattern of geometric shapes in bold, contrasting colors to create a dynamic, eye-catching design.',
  'An abstract pattern featuring bold, graphic brush strokes in a monochromatic color scheme, perfect for a minimalist yet artistic shirt.',
  'A pattern of stylized waves or ocean-inspired designs in a limited color palette, perfect for a beach or surf-themed shirt.',
  'A pattern of strong, graphic lines or stripes in a bold, monochromatic design with a minimalist vibe.',
  'A pattern of bold, graphic arrows or chevrons in a striking color scheme to create a dynamic, directional design.',
  'A pattern of abstract geometric shapes in a monochromatic color scheme with a distressed texture to give a vintage, retro-inspired vibe.',
  'A repeating pattern of bold, graphic flowers or foliage in a limited color palette to create a natural, organic feel.',
  'A pattern of strong, graphic dots or circles in a bold, monochromatic design with a modern, minimalist vibe.',
  'A pattern of stylized mountains or landscapes in a limited color palette, perfect for an outdoors or adventure-themed shirt.',
  'A pattern of bold, graphic lightning bolts or thunder in a dynamic, energetic design with sharp lines and a striking color scheme.',
  'A repeating pattern of stylized animal prints, such as zebra or leopard, in a limited color palette to create an edgy, urban vibe.',
  'A pattern of bold, graphic shapes in a colorful, kaleidoscope-inspired design to create a psychedelic, retro vibe.',
  'A pattern of strong, graphic triangles or other geometric shapes in a bold, monochromatic design with a modern, minimalist feel.',
  'A pattern of stylized flames or fire-inspired designs in a vibrant color scheme to create a hot rod or racing-inspired shirt.',
  'A pattern of bold, graphic stars or constellations in a dark color scheme to create a cosmic, otherworldly vibe.',
  'A pattern of stylized camouflage in a limited color palette, perfect for an outdoors or military-inspired shirt.',
  'A repeating pattern of bold, graphic text in a monochromatic design with a minimalist vibe.',
  'A pattern of strong, graphic lightning bolts or thunder in a dynamic, energetic design with sharp lines and a striking color scheme.',
  'A pattern of stylized musical notes or instruments in a limited color palette, perfect for a music-inspired shirt.',
  'A pattern of bold, graphic sports equipment or athletic motifs in a striking color scheme to create a sporty, active vibe.',
  'An animal-inspired logo featuring a fierce lion or tiger in a minimalist style with sharp, clean lines and bold contrast.',
  'A logo that incorporates a stylized arrow or compass in a sleek, modern design with a striking color palette.',
  'A logo that features an abstract mountain range with clean, simple lines and a muted color scheme to give a minimalist, outdoorsy vibe.',
  'A logo that incorporates a skull or bones in a bold, grunge-inspired design with distressed textures and a vintage color scheme.',
  'A logo that incorporates a bold eagle or hawk with strong, sharp lines and a sleek, modern design in a striking monochrome color scheme.',
  'A logo that features a stylized bike or motorcycle in a vintage, retro-inspired design with bold typography and a limited color palette.',
  'A logo that incorporates a strong, geometric shape like a diamond or hexagon in a bold, minimalist design with a striking color palette.',
  'A logo that features a stylized anchor in a sleek, modern design with bold typography and a limited color palette, perfect for a nautical-themed shirt.',
  'A logo that incorporates a strong, graphic tree or leaf design in a modern, minimalistic style with clean lines and a muted color palette.',
  'A logo that incorporates a stylized skull with geometric shapes in a bold, modern design with a limited color palette, perfect for a edgy or rocker-inspired shirt.',
  'A logo that features a strong, graphic wolf or bear design in a minimalist style with bold typography and a striking color palette.',
  'A logo that incorporates a stylized lightning bolt in a sleek, modern design with a vibrant color palette, perfect for a sporty or athletic shirt.',
  'A logo that features a stylized bird, such as an eagle or falcon, in a dynamic, energetic design with sharp lines and a bold color scheme.',
  'A logo that incorporates a strong, geometric shape like a triangle or pentagon in a clean, minimalist design with a muted color palette.',
  'A logo that features a stylized guitar or musical instrument in a vintage, retro-inspired design with bold typography and a limited color palette.',
  'A logo that incorporates a bold, graphic flame design in a sleek, modern design with a striking color palette, perfect for a hot rod or racing-themed shirt.',
  'A logo that features a stylized skull with wings or other Gothic elements in a bold, grunge-inspired design with distressed textures and a vintage color scheme.',
  'A logo that incorporates a strong, graphic anchor in a minimalist design with bold typography and a limited color palette, perfect for a nautical-themed shirt.',
  'A logo that features a stylized bear claw or other animal-inspired design in a dynamic, energetic design with bold lines and a vibrant color scheme.',
  'A logo that incorporates a stylized mountain range or forest in a sleek, modern design with a muted color palette, perfect for an outdoors-inspired shirt.',
  'A logo that features a strong, graphic wolf or bear paw design in a minimalist style with bold typography and a striking color palette.',
  'A logo that incorporates a stylized lightning bolt or thunder in a dynamic, energetic design with sharp lines and a bold color scheme.',
  'A logo that features a stylized eagle or falcon with spread wings in a sleek, modern design with a limited color palette, perfect for a sporty or athletic shirt.',
  'A logo that incorporates a strong, geometric shape like a circle or hexagon in a clean, minimalist design with a bold color palette.',
  'A logo that features a stylized skull with snake or serpent elements in a bold, grunge-inspired design with distressed textures and a vintage color scheme.',
  'A logo that incorporates a bold, graphic tire design in a sleek, modern design with a striking color palette, perfect for a car or racing-themed shirt.',
  'A logo that features a stylized anchor with a rope or other nautical elements in a minimalist design with bold typography and a limited color palette.',
  'A logo that incorporates a strong, graphic wolf or bear face design in a dynamic, energetic style with bold lines and a vibrant color scheme.',
  'A logo that features a stylized surfboard or wave design in a vintage, retro-inspired style with bold typography and a limited color palette, perfect for a beach or surf-themed shirt.',
];
